cd adult/
python Ouralgonb.py
python Ouralgo_nog.py
cd ../tweets
python Ouralgonb.py
python Ouralgo_nog.py
cd ../bmi
python Ouralgonb.py
python Ouralgo_nog.py
#python Ouralgo.py
cd ../flights
python Ouralgonb.py
python Ouralgo_nog.py
#python Ouralgo_new.py
cd ../amazon
python Ouralgonb.py
python Ouralgo_nog.py
#python Ouralgo.py
cd ../opendata
python Ouralgonb.py
python Ouralgo_nog.py
#python Ouralgo.py
cd ../physicians
python Ouralgonb.py
python Ouralgo_nog.py
#python Ouralgo.py
cd ../
python read_output_fig7.py
